### ISSUE TITLE
Find every site that has raspberry pi's and accessories for it

### ISSUE THREAD

**Issue by pozharliev** [ABPozharliev19/raspberry-pi-shop#2]
As a developer I need every site that has/sells raspberry pi's so we can later crawl them.

**Comment by MCBerberov19** [comment]
[First](https://www.digikey.com/en/products/result?s=N4IgTCBcDaIE4EMDOAHARgUznAngAhQEsQBdAXyA)
[Second](https://www.newark.com/buy-raspberry-pi)
[Third](https://www.picocluster.com/collections/raspberry-pi4)
~amazon
[Fourth](https://www.adafruit.com/category/105)
[Fifth](https://thepihut.com/collections/raspberry-pi)
[Sixth](https://www.robotev.com/index.php?cPath=1_48&sort=1a&page=1&osCsid=6ad79jlni5663lgr6vegbrp1h0)
[Seventh](https://www.mobilestore.bg/Raspberry-Pi)
[Eighth](https://bg.farnell.com/c/embedded-computers-education-maker-boards/raspberry-pi)
